version: '3'
services:
    web:
        build:
            dockerfile: Dockerfile.web
            context: .
        environment:
            - API_KEY
            - REDIS_HOST=redis
            - PRERENDER_HOST=prerender
            - PRERENDER_PORT=3000
        ports:
            - 5000:5000
    worker:
        build:
            dockerfile: Dockerfile.worker
            context: .
        environment:
            - API_KEY
            - REDIS_HOST=redis
            - PRERENDER_HOST=prerender
            - PRERENDER_PORT=3000
        user: nobody
    redis:
        image: "redis:alpine"
    prerender:
        image: "magnetme/prerender-docker"
    arpa:
        build: "https://github.com/SemanticComputing/arpa-docker.git"
        environment:
            - analyze_address=http://las:9000/las/analyze
        volumes:
            - ./arpa_conf/:/opt/arpa/services
        ports:
            - 19991:9000
    las:
        image: "jiemakel/las-ws:1.1"
        ports:
            - 19990:9000
