version: '3.5'
services:
    frontend:
        build: https://github.com/SemanticComputing/relevance-feedback-frontend.git
        ports:
            - 3000:5000
    web:
        build:
            dockerfile: Dockerfile.web
            context: .
        environment:
            - API_KEY
            - REDIS_HOST=redis
            - PRERENDER_HOST=prerender
            - PRERENDER_PORT=3000
            - ARPA_URL=http://arpa:9000/koko-related
        ports:
            - 5000:5000
    worker:
        build:
            dockerfile: Dockerfile.worker
            context: .
        environment:
            - API_KEY
            - REDIS_HOST=redis
            - PRERENDER_HOST=prerender
            - PRERENDER_PORT=3000
            - ARPA_URL=http://arpa:9000/koko-related
            - BASEFORM_URL=http://las:9000/las/baseform
        user: nobody
    redis:
        image: redis:alpine
    prerender:
        build: https://github.com/SemanticComputing/prerender-docker.git#relevance-feedback
        shm_size: 5gb
    arpa:
        image: jiemakel/arpa:1.0
        environment:
            - ANALYZE_ADDRESS=http://las:9000/las/analyze
        volumes:
            - ./arpa_conf/:/opt/docker/services
    las:
        image: jiemakel/las-ws:1.1
        ports:
            - 9000:9000
    elastic:
        build: ./elastic
        volumes:
            - hades_esdata:/usr/share/elasticsearch/data

volumes:
    hades_esdata:
        external: true
